$ GRAPH == "PRINT/QUEUE=POST$LSR1"
$ LA80 == "PRINT/NOTIFY/HEADER/QUEUE=SYS$LSR0/PARAMETER=(NUMBER_UP=2)"
$ COFFEE80 == "PRINT/NOTIFY/HEADER/QUEUE=SYS$LSR1/PARAMETER=(NUMBER_UP=2)"
$ LA132=="PRINT/NOTIFY/QUEUE=SYS$LSR0/PARAMETER=-
  (NUMBER_UP=2,PAGE_ORIENTATION=LANDSCAPE)"
